### ISSUE TITLE
Request for interesting math?

### ISSUE THREAD

**Issue by j2kun** [UnstableDesign/AdaCAD-UI#112]
Hi there,

I'm writing a book about math used in production software (https://pmfpbook.org). I came across this project after seeing a talk by [Lea Albaugh](http://lea.zone/blog/category/textiles/), and I was wondering what sort of interesting math and/or algorithms are used in AdaCAD. I'm guessing there might be something related to planning/optimizing a thread configuration?

I'm particularly interested in the problems that produced the need for the math, and in the story of how the weavers/programmers involved grappled with understanding and applying the math to make AdaCAD better.

If there's something worth writing about in this context, I would also love to interview someone who was involved in the work (30 minutes phone/video call). If all goes well, it will go into my book and AdaCAD can get some free advertising out of it :)

At the least, it would help if you could point me to where in the source tree you think there might be interesting algorithms/math for me to read about. Or if you have any references to other projects in the fiber arts space that might be relevant for this book, I'd appreciate hearing about it!

**Comment by sminliwu** [comment]
Hi! Your project sounds super interesting, and I could definitely point you to some math connections in weaving. Generally, when a weaver selects/creates/designs/modifies a draft (draft = the bitmap file, design = draft + other parts like yarn choices), they're plotting out a set of possible design elements. I'm really rusty on my combinatorics, but I hope that might suggest how weavers traditionally are performing lots of algebra. I'm thinking mostly of shaft loom weaving, but this applies to many types of looms.

You might find these sources useful:
http://fiberarts.org/design/articles/algebra.html
https://www2.cs.arizona.edu/patterns/weaving/webdocs/wa_mr.pdf (generally check out the weaving archives at https://www2.cs.arizona.edu/patterns/weaving/)
https://zenodo.org/record/3342554#.Y_Oz4HbMK3A (generally check out the PENELOPE project https://zenodo.org/communities/penelope/)

I can talk for days about weaving math, so feel free to drop me a line at shanel.wu@colorado.edu, and you might also have more luck reaching more of the lab at unstabledesignlab@gmail.com.

**Comment by j2kun** [comment]
Thanks for the resources! I'll study them and let you know if I'd like to chat about any of them. Closing the issue for now.
